# Generated by Django 5.0.6 on 2024-06-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gender',
            new_name='genre',
        ),
    ]
