# Generated by Django 5.0.6 on 2024-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_gender_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
